# First we are gonna load the packages

```{r}
# Load necessary packages
library(rstan)
library(coda)
library(R2jags)


setwd("/home/rstudio/notas3Ejemplos")
source("../DBDA2Eprograms/DBDA2E-utilities.R")

# set the working directory

```

# Trabajeremos con lo siguiente
```{r}
#-Reading data-
utilidad<-c(212, 207, 210,
196, 223, 193,
196, 210, 202, 221)
n<-length(utilidad)

#-Defining data-
data<-list("n"=n,"x"=utilidad)

```

## primero lo haremos en jaggs
```{r}


#-Defining inits-
inits<-function(){list(mu=0,sig=1,x1=0)}

#-Selecting parameters to monitor-
parameters<-c("mu","sig","x1")

#-Running code-
#OpenBUGS
#ej2.sim<-bugs(data,inits,parameters,model.file="Ej2.txt",
#              n.iter=5000,n.chains=2,n.burnin=500)
#JAGS
ej2.sim<-jags(data,inits,parameters,model.file="Ej2.txt",
              n.iter=5000,n.chains=2,n.burnin=500,n.thin=1)

#-Monitoring chain-

#Traza de la cadena
traceplot(ej2.sim)

#Multiples cadenas

#OpenBUGS
#out.a<-ej2.sim$sims.array

#JAGS
out.a<-ej2.sim$BUGSoutput$sims.array

z1<-out.a[,1,1]
z2<-out.a[,2,1]
par(mfrow=c(3,2))
plot(z1,type="l",col="grey50")
lines(z2,col="firebrick2")
y1<-cumsum(z1)/(1:length(z1))
y2<-cumsum(z2)/(1:length(z2))
ymin<-min(y1,y2)
ymax<-max(y1,y2)
plot(y1,type="l",col="grey50",ylim=c(ymin,ymax))
lines(y2,col="firebrick2",ylim=c(ymin,ymax))
hist(z1,freq=FALSE,col="grey50")
hist(z2,freq=FALSE,col="firebrick2")
acf(z1)
acf(z2)

#Resumen (estimadores)
#OpenBUGS
#out.sum<-ej2.sim$summary

#JAGS
out.sum<-ej2.sim$BUGSoutput$summary

print(out.sum)

#DIC
#OpenBUGS
#out.dic<-ej2.sim$DIC

#JAGS
out.dic<-ej2.sim$BUGSoutput$DIC

print(out.dic)

```

## ahora lo haremos con rstan

```{r}
set.seed(1)
#-Defining inits-
inits<-function(){list(mu=0,sig=1)}
# Compiling model
stan_model <- stan_model("Ej2.stan")

# Running the model
stan_fit <- sampling(stan_model, data = data, init = inits, 
                      pars = c("mu", "sig"), chains = 2, 
                      iter = 5000, warmup = 500)

# Monitoring chain
print(stan_fit)

# Traceplot
# Extract MCMC chains from stanfit object
chains <- as.matrix(stan_fit)

# Extract relevant columns for traceplot
theta_chains <- chains[, "mu"]
phi_chains <- chains[, "sig"]

# Plot trace and density plots
traceplot(as.mcmc(theta_chains))
traceplot(as.mcmc(phi_chains))


# Posterior summary
summary(stan_fit)

# Computing DIC  (CHECK)
dic <- stan_fit@simoutput$diagnostics$summary$DIC
print(dic)


# Predictive posterior
ppc <- posterior_predict(stan_fit)
y_pred <- colMeans(ppc)
print(y_pred)
```

## comparando convergencia de otra forma

```{r}
# Convert stan format to coda format:
mcmcCoda = mcmc.list( lapply( 1:ncol(stan_fit) ,
                              function(x) { mcmc(as.array(stan_fit)[,x,]) } ) )
# Graph chain diagnostics using DBDA2E function:

diagMCMC( mcmcCoda , parName=c("sig") )

```
